import fs from 'node:fs';
import path from 'node:path';
import { instanceDir } from '../utils/paths.js';
import type { Platform } from '../types/index.js';

function propertiesFileFor(platform: Platform): string {
  return 'server.properties';
}

/** Parses a Java-properties-style file (key=value, # comments) into an ordered array of entries. */
export function parseProperties(text: string): { key: string; value: string }[] {
  const entries: { key: string; value: string }[] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf('=');
    if (idx === -1) continue;
    entries.push({ key: line.slice(0, idx).trim(), value: line.slice(idx + 1) });
  }
  return entries;
}

export function readServerProperties(serverId: string, platform: Platform): { key: string; value: string }[] {
  const filePath = path.join(instanceDir(serverId), propertiesFileFor(platform));
  if (!fs.existsSync(filePath)) return [];
  return parseProperties(fs.readFileSync(filePath, 'utf8'));
}

/** Rewrites server.properties, preserving existing key order and appending any new keys. */
export function writeServerProperties(
  serverId: string,
  platform: Platform,
  updates: Record<string, string>
): void {
  const filePath = path.join(instanceDir(serverId), propertiesFileFor(platform));
  const existingText = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  const lines = existingText.split(/\r?\n/);
  const seen = new Set<string>();
  const output: string[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      output.push(rawLine);
      continue;
    }
    const idx = line.indexOf('=');
    if (idx === -1) {
      output.push(rawLine);
      continue;
    }
    const key = line.slice(0, idx).trim();
    if (Object.prototype.hasOwnProperty.call(updates, key)) {
      output.push(`${key}=${updates[key]}`);
      seen.add(key);
    } else {
      output.push(rawLine);
    }
  }

  for (const [key, value] of Object.entries(updates)) {
    if (!seen.has(key)) output.push(`${key}=${value}`);
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, output.join('\n'));
}

export function writeEula(serverId: string, accepted: boolean): void {
  const filePath = path.join(instanceDir(serverId), 'eula.txt');
  const content = `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).\n#Generated by MultiCraft\neula=${accepted ? 'true' : 'false'}\n`;
  fs.writeFileSync(filePath, content);
}
